-- RetailIQ deployment user for Streamlit on Cloud Run.
-- Run this as ACCOUNTADMIN after replacing <paste_public_key_here>.
-- The app user is read-only and authenticates with Snowflake key-pair auth.

USE ROLE ACCOUNTADMIN;

CREATE ROLE IF NOT EXISTS RETAILIQ_APP_ROLE;

GRANT USAGE ON WAREHOUSE RETAILIQ_WH TO ROLE RETAILIQ_APP_ROLE;
GRANT USAGE ON DATABASE RETAILIQ_DB TO ROLE RETAILIQ_APP_ROLE;

GRANT USAGE ON SCHEMA RETAILIQ_DB.RAW TO ROLE RETAILIQ_APP_ROLE;
GRANT USAGE ON SCHEMA RETAILIQ_DB.STAGING TO ROLE RETAILIQ_APP_ROLE;
GRANT USAGE ON SCHEMA RETAILIQ_DB.MARTS TO ROLE RETAILIQ_APP_ROLE;
GRANT USAGE ON SCHEMA RETAILIQ_DB.ML TO ROLE RETAILIQ_APP_ROLE;
GRANT USAGE ON SCHEMA RETAILIQ_DB.ANALYTICS TO ROLE RETAILIQ_APP_ROLE;

GRANT SELECT ON ALL TABLES IN SCHEMA RETAILIQ_DB.RAW TO ROLE RETAILIQ_APP_ROLE;
GRANT SELECT ON ALL TABLES IN SCHEMA RETAILIQ_DB.MARTS TO ROLE RETAILIQ_APP_ROLE;
GRANT SELECT ON ALL TABLES IN SCHEMA RETAILIQ_DB.ML TO ROLE RETAILIQ_APP_ROLE;
GRANT SELECT ON ALL VIEWS IN SCHEMA RETAILIQ_DB.STAGING TO ROLE RETAILIQ_APP_ROLE;
GRANT SELECT ON ALL VIEWS IN SCHEMA RETAILIQ_DB.MARTS TO ROLE RETAILIQ_APP_ROLE;

GRANT SELECT ON FUTURE TABLES IN SCHEMA RETAILIQ_DB.RAW TO ROLE RETAILIQ_APP_ROLE;
GRANT SELECT ON FUTURE TABLES IN SCHEMA RETAILIQ_DB.MARTS TO ROLE RETAILIQ_APP_ROLE;
GRANT SELECT ON FUTURE TABLES IN SCHEMA RETAILIQ_DB.ML TO ROLE RETAILIQ_APP_ROLE;
GRANT SELECT ON FUTURE VIEWS IN SCHEMA RETAILIQ_DB.STAGING TO ROLE RETAILIQ_APP_ROLE;
GRANT SELECT ON FUTURE VIEWS IN SCHEMA RETAILIQ_DB.MARTS TO ROLE RETAILIQ_APP_ROLE;

CREATE USER IF NOT EXISTS RETAILIQ_APP_USER
    TYPE = SERVICE
    LOGIN_NAME = 'RETAILIQ_APP_USER'
    DEFAULT_ROLE = RETAILIQ_APP_ROLE
    DEFAULT_WAREHOUSE = RETAILIQ_WH
    DEFAULT_NAMESPACE = RETAILIQ_DB.MARTS
    COMMENT = 'Service user for the RetailIQ Cloud Run Streamlit application.';

ALTER USER RETAILIQ_APP_USER SET RSA_PUBLIC_KEY = '<paste_public_key_here>';

GRANT ROLE RETAILIQ_APP_ROLE TO USER RETAILIQ_APP_USER;
