-- Optional role model for RetailIQ development.
-- Adjust role names, user grants, and security policies for your Snowflake account.

USE ROLE SECURITYADMIN;

CREATE ROLE IF NOT EXISTS RETAILIQ_ADMIN;
CREATE ROLE IF NOT EXISTS RETAILIQ_LOADER;
CREATE ROLE IF NOT EXISTS RETAILIQ_TRANSFORMER;
CREATE ROLE IF NOT EXISTS RETAILIQ_ANALYST;

USE ROLE SYSADMIN;

GRANT USAGE ON WAREHOUSE RETAILIQ_WH TO ROLE RETAILIQ_ADMIN;
GRANT USAGE ON WAREHOUSE RETAILIQ_WH TO ROLE RETAILIQ_LOADER;
GRANT USAGE ON WAREHOUSE RETAILIQ_WH TO ROLE RETAILIQ_TRANSFORMER;
GRANT USAGE ON WAREHOUSE RETAILIQ_WH TO ROLE RETAILIQ_ANALYST;

GRANT USAGE ON DATABASE RETAILIQ_DB TO ROLE RETAILIQ_ADMIN;
GRANT USAGE ON DATABASE RETAILIQ_DB TO ROLE RETAILIQ_LOADER;
GRANT USAGE ON DATABASE RETAILIQ_DB TO ROLE RETAILIQ_TRANSFORMER;
GRANT USAGE ON DATABASE RETAILIQ_DB TO ROLE RETAILIQ_ANALYST;

GRANT USAGE ON SCHEMA RETAILIQ_DB.RAW TO ROLE RETAILIQ_LOADER;
GRANT INSERT, SELECT ON ALL TABLES IN SCHEMA RETAILIQ_DB.RAW TO ROLE RETAILIQ_LOADER;
GRANT INSERT, SELECT ON FUTURE TABLES IN SCHEMA RETAILIQ_DB.RAW TO ROLE RETAILIQ_LOADER;

GRANT USAGE ON ALL SCHEMAS IN DATABASE RETAILIQ_DB TO ROLE RETAILIQ_TRANSFORMER;
GRANT SELECT ON ALL TABLES IN SCHEMA RETAILIQ_DB.RAW TO ROLE RETAILIQ_TRANSFORMER;
GRANT CREATE TABLE, CREATE VIEW ON SCHEMA RETAILIQ_DB.STAGING TO ROLE RETAILIQ_TRANSFORMER;
GRANT CREATE TABLE, CREATE VIEW ON SCHEMA RETAILIQ_DB.MARTS TO ROLE RETAILIQ_TRANSFORMER;
GRANT CREATE TABLE, CREATE VIEW ON SCHEMA RETAILIQ_DB.ML TO ROLE RETAILIQ_TRANSFORMER;

GRANT USAGE ON SCHEMA RETAILIQ_DB.MARTS TO ROLE RETAILIQ_ANALYST;
GRANT USAGE ON SCHEMA RETAILIQ_DB.ANALYTICS TO ROLE RETAILIQ_ANALYST;
GRANT SELECT ON ALL TABLES IN SCHEMA RETAILIQ_DB.MARTS TO ROLE RETAILIQ_ANALYST;
GRANT SELECT ON ALL TABLES IN SCHEMA RETAILIQ_DB.ANALYTICS TO ROLE RETAILIQ_ANALYST;
GRANT SELECT ON FUTURE TABLES IN SCHEMA RETAILIQ_DB.MARTS TO ROLE RETAILIQ_ANALYST;
GRANT SELECT ON FUTURE TABLES IN SCHEMA RETAILIQ_DB.ANALYTICS TO ROLE RETAILIQ_ANALYST;

