-- RetailIQ Airflow pipeline user.
-- Run this as ACCOUNTADMIN after replacing <paste_public_key_here>.
--
-- This user is intentionally separate from RETAILIQ_APP_USER:
-- - RETAILIQ_APP_USER is read-only for the public Streamlit app.
-- - RETAILIQ_AIRFLOW_USER can load RAW/ML data and rebuild dbt models.

USE ROLE ACCOUNTADMIN;

CREATE ROLE IF NOT EXISTS RETAILIQ_PIPELINE_ROLE;

GRANT USAGE ON WAREHOUSE RETAILIQ_WH TO ROLE RETAILIQ_PIPELINE_ROLE;
GRANT USAGE ON DATABASE RETAILIQ_DB TO ROLE RETAILIQ_PIPELINE_ROLE;
GRANT CREATE SCHEMA ON DATABASE RETAILIQ_DB TO ROLE RETAILIQ_PIPELINE_ROLE;

GRANT USAGE ON SCHEMA RETAILIQ_DB.RAW TO ROLE RETAILIQ_PIPELINE_ROLE;
GRANT USAGE ON SCHEMA RETAILIQ_DB.STAGING TO ROLE RETAILIQ_PIPELINE_ROLE;
GRANT USAGE ON SCHEMA RETAILIQ_DB.MARTS TO ROLE RETAILIQ_PIPELINE_ROLE;
GRANT USAGE ON SCHEMA RETAILIQ_DB.ML TO ROLE RETAILIQ_PIPELINE_ROLE;
GRANT USAGE ON SCHEMA RETAILIQ_DB.ANALYTICS TO ROLE RETAILIQ_PIPELINE_ROLE;

GRANT CREATE STAGE ON SCHEMA RETAILIQ_DB.RAW TO ROLE RETAILIQ_PIPELINE_ROLE;
GRANT CREATE STAGE ON SCHEMA RETAILIQ_DB.ML TO ROLE RETAILIQ_PIPELINE_ROLE;
GRANT CREATE TABLE ON SCHEMA RETAILIQ_DB.ML TO ROLE RETAILIQ_PIPELINE_ROLE;

GRANT SELECT, INSERT, TRUNCATE ON ALL TABLES IN SCHEMA RETAILIQ_DB.RAW TO ROLE RETAILIQ_PIPELINE_ROLE;
GRANT SELECT, INSERT, TRUNCATE ON FUTURE TABLES IN SCHEMA RETAILIQ_DB.RAW TO ROLE RETAILIQ_PIPELINE_ROLE;

GRANT SELECT, INSERT, TRUNCATE ON ALL TABLES IN SCHEMA RETAILIQ_DB.ML TO ROLE RETAILIQ_PIPELINE_ROLE;
GRANT SELECT, INSERT, TRUNCATE ON FUTURE TABLES IN SCHEMA RETAILIQ_DB.ML TO ROLE RETAILIQ_PIPELINE_ROLE;

GRANT CREATE TABLE, CREATE VIEW ON SCHEMA RETAILIQ_DB.STAGING TO ROLE RETAILIQ_PIPELINE_ROLE;
GRANT CREATE TABLE, CREATE VIEW ON SCHEMA RETAILIQ_DB.MARTS TO ROLE RETAILIQ_PIPELINE_ROLE;

GRANT SELECT ON ALL TABLES IN SCHEMA RETAILIQ_DB.RAW TO ROLE RETAILIQ_PIPELINE_ROLE;
GRANT SELECT ON FUTURE TABLES IN SCHEMA RETAILIQ_DB.RAW TO ROLE RETAILIQ_PIPELINE_ROLE;
GRANT SELECT ON ALL TABLES IN SCHEMA RETAILIQ_DB.ML TO ROLE RETAILIQ_PIPELINE_ROLE;
GRANT SELECT ON FUTURE TABLES IN SCHEMA RETAILIQ_DB.ML TO ROLE RETAILIQ_PIPELINE_ROLE;
GRANT SELECT ON ALL TABLES IN SCHEMA RETAILIQ_DB.MARTS TO ROLE RETAILIQ_PIPELINE_ROLE;
GRANT SELECT ON FUTURE TABLES IN SCHEMA RETAILIQ_DB.MARTS TO ROLE RETAILIQ_PIPELINE_ROLE;
GRANT SELECT ON ALL VIEWS IN SCHEMA RETAILIQ_DB.STAGING TO ROLE RETAILIQ_PIPELINE_ROLE;
GRANT SELECT ON FUTURE VIEWS IN SCHEMA RETAILIQ_DB.STAGING TO ROLE RETAILIQ_PIPELINE_ROLE;
GRANT SELECT ON ALL VIEWS IN SCHEMA RETAILIQ_DB.MARTS TO ROLE RETAILIQ_PIPELINE_ROLE;
GRANT SELECT ON FUTURE VIEWS IN SCHEMA RETAILIQ_DB.MARTS TO ROLE RETAILIQ_PIPELINE_ROLE;

-- If dbt models already exist from ACCOUNTADMIN or another role, uncomment these
-- ownership grants once so RETAILIQ_PIPELINE_ROLE can replace them during dbt run.
-- GRANT OWNERSHIP ON ALL TABLES IN SCHEMA RETAILIQ_DB.STAGING TO ROLE RETAILIQ_PIPELINE_ROLE COPY CURRENT GRANTS;
-- GRANT OWNERSHIP ON ALL VIEWS IN SCHEMA RETAILIQ_DB.STAGING TO ROLE RETAILIQ_PIPELINE_ROLE COPY CURRENT GRANTS;
-- GRANT OWNERSHIP ON ALL TABLES IN SCHEMA RETAILIQ_DB.MARTS TO ROLE RETAILIQ_PIPELINE_ROLE COPY CURRENT GRANTS;
-- GRANT OWNERSHIP ON ALL VIEWS IN SCHEMA RETAILIQ_DB.MARTS TO ROLE RETAILIQ_PIPELINE_ROLE COPY CURRENT GRANTS;
-- GRANT OWNERSHIP ON ALL TABLES IN SCHEMA RETAILIQ_DB.ML TO ROLE RETAILIQ_PIPELINE_ROLE COPY CURRENT GRANTS;

CREATE USER IF NOT EXISTS RETAILIQ_AIRFLOW_USER
    TYPE = SERVICE
    LOGIN_NAME = 'RETAILIQ_AIRFLOW_USER'
    DEFAULT_ROLE = RETAILIQ_PIPELINE_ROLE
    DEFAULT_WAREHOUSE = RETAILIQ_WH
    DEFAULT_NAMESPACE = RETAILIQ_DB.RAW
    COMMENT = 'Service user for local RetailIQ Airflow pipeline runs.';

ALTER USER RETAILIQ_AIRFLOW_USER SET RSA_PUBLIC_KEY = '<paste_public_key_here>';

GRANT ROLE RETAILIQ_PIPELINE_ROLE TO USER RETAILIQ_AIRFLOW_USER;
