-- RetailIQ dbt ownership repair.
--
-- Run this as ACCOUNTADMIN if dbt fails with:
-- "object already exists, but current role has no privileges on it."
--
-- Why this is needed:
-- Earlier manual dbt runs may have created STAGING and MARTS objects as
-- ACCOUNTADMIN. Airflow uses RETAILIQ_PIPELINE_ROLE, so dbt needs ownership
-- of those existing objects before it can replace them on each pipeline run.

USE ROLE ACCOUNTADMIN;

GRANT OWNERSHIP ON ALL TABLES IN SCHEMA RETAILIQ_DB.STAGING
  TO ROLE RETAILIQ_PIPELINE_ROLE
  COPY CURRENT GRANTS;

GRANT OWNERSHIP ON ALL VIEWS IN SCHEMA RETAILIQ_DB.STAGING
  TO ROLE RETAILIQ_PIPELINE_ROLE
  COPY CURRENT GRANTS;

GRANT OWNERSHIP ON ALL TABLES IN SCHEMA RETAILIQ_DB.MARTS
  TO ROLE RETAILIQ_PIPELINE_ROLE
  COPY CURRENT GRANTS;

GRANT OWNERSHIP ON ALL VIEWS IN SCHEMA RETAILIQ_DB.MARTS
  TO ROLE RETAILIQ_PIPELINE_ROLE
  COPY CURRENT GRANTS;

GRANT OWNERSHIP ON ALL TABLES IN SCHEMA RETAILIQ_DB.ML
  TO ROLE RETAILIQ_PIPELINE_ROLE
  COPY CURRENT GRANTS;

-- Keep future objects manageable by the pipeline role.
GRANT CREATE TABLE, CREATE VIEW ON SCHEMA RETAILIQ_DB.STAGING TO ROLE RETAILIQ_PIPELINE_ROLE;
GRANT CREATE TABLE, CREATE VIEW ON SCHEMA RETAILIQ_DB.MARTS TO ROLE RETAILIQ_PIPELINE_ROLE;
GRANT CREATE TABLE, CREATE STAGE ON SCHEMA RETAILIQ_DB.ML TO ROLE RETAILIQ_PIPELINE_ROLE;

-- Keep dashboard/app roles able to read dbt outputs after ownership changes.
GRANT SELECT ON ALL TABLES IN SCHEMA RETAILIQ_DB.MARTS TO ROLE RETAILIQ_PIPELINE_ROLE;
GRANT SELECT ON ALL VIEWS IN SCHEMA RETAILIQ_DB.MARTS TO ROLE RETAILIQ_PIPELINE_ROLE;
GRANT SELECT ON ALL TABLES IN SCHEMA RETAILIQ_DB.ML TO ROLE RETAILIQ_PIPELINE_ROLE;
