-- RetailIQ Snowflake foundation
-- Run with a role that can create databases, schemas, warehouses, and tables.

CREATE WAREHOUSE IF NOT EXISTS RETAILIQ_WH
  WAREHOUSE_SIZE = XSMALL
  AUTO_SUSPEND = 60
  AUTO_RESUME = TRUE
  INITIALLY_SUSPENDED = TRUE
  COMMENT = 'XSMALL warehouse for RetailIQ development workloads';

CREATE DATABASE IF NOT EXISTS RETAILIQ_DB
  COMMENT = 'RetailIQ demand intelligence warehouse';

CREATE SCHEMA IF NOT EXISTS RETAILIQ_DB.RAW
  COMMENT = 'Raw ingested source data';

CREATE SCHEMA IF NOT EXISTS RETAILIQ_DB.STAGING
  COMMENT = 'Cleaned and typed staging models';

CREATE SCHEMA IF NOT EXISTS RETAILIQ_DB.MARTS
  COMMENT = 'Analytics-ready dimensional and fact models';

CREATE SCHEMA IF NOT EXISTS RETAILIQ_DB.ML
  COMMENT = 'Machine learning features, predictions, and model outputs';

CREATE SCHEMA IF NOT EXISTS RETAILIQ_DB.ANALYTICS
  COMMENT = 'Dashboard and AI analyst serving layer';

CREATE TABLE IF NOT EXISTS RETAILIQ_DB.RAW.SALES (
  STORE NUMBER,
  DEPT NUMBER,
  DATE DATE,
  WEEKLY_SALES FLOAT,
  IS_HOLIDAY BOOLEAN,
  SOURCE_FILE VARCHAR,
  LOADED_AT TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP()
);

CREATE TABLE IF NOT EXISTS RETAILIQ_DB.RAW.STORES (
  STORE NUMBER,
  STORE_TYPE VARCHAR,
  SIZE NUMBER,
  SOURCE_FILE VARCHAR,
  LOADED_AT TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP()
);

CREATE TABLE IF NOT EXISTS RETAILIQ_DB.RAW.FEATURES (
  STORE NUMBER,
  DATE DATE,
  TEMPERATURE FLOAT,
  FUEL_PRICE FLOAT,
  MARKDOWN1 FLOAT,
  MARKDOWN2 FLOAT,
  MARKDOWN3 FLOAT,
  MARKDOWN4 FLOAT,
  MARKDOWN5 FLOAT,
  CPI FLOAT,
  UNEMPLOYMENT FLOAT,
  IS_HOLIDAY BOOLEAN,
  SOURCE_FILE VARCHAR,
  LOADED_AT TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP()
);

CREATE TABLE IF NOT EXISTS RETAILIQ_DB.RAW.INVENTORY (
  STORE NUMBER,
  DEPT NUMBER,
  DATE DATE,
  SKU VARCHAR,
  AVAILABLE_INVENTORY FLOAT,
  SAFETY_STOCK_UNITS FLOAT,
  REORDER_POINT_UNITS FLOAT,
  SOURCE_FILE VARCHAR,
  LOADED_AT TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP()
);

CREATE TABLE IF NOT EXISTS RETAILIQ_DB.RAW.WEATHER (
  STORE NUMBER,
  DATE DATE,
  TEMPERATURE FLOAT,
  PRECIPITATION FLOAT,
  SNOWFALL FLOAT,
  SOURCE_FILE VARCHAR,
  LOADED_AT TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP()
);

